name: customer-churn-env

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - pip:
      - mlflow
      - scikit-learn
      - pandas
      - seaborn
      - matplotlib
      - dagshub
